name: imagy
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py310hca03da5_1
  - aiohappyeyeballs=2.6.1=py310hca03da5_0
  - aiohttp=3.13.3=py310haa24f5a_0
  - aiosignal=1.4.0=py310hca03da5_0
  - anyio=4.10.0=py310hca03da5_0
  - aom=3.12.1=ha237518_0
  - arrow-cpp=21.0.0=hc027f7d_2
  - async-timeout=5.0.1=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310h03d0aa3_1
  - brotlicffi=1.2.0.0=py310h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.01.04=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cycler=0.12.1=py310hca03da5_0
  - datasets=4.4.1=py310hca03da5_1
  - dav1d=1.2.1=h80987f9_0
  - dill=0.4.0=py310hca03da5_0
  - exceptiongroup=1.3.0=py310hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.3=py310hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py310haa24f5a_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - frozenlist=1.8.0=py310h50f4ffc_0
  - fsspec=2025.10.0=py310h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.2=py310hbcc4bda_0
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py310hca03da5_1
  - harfbuzz=12.3.0=h9837a22_1
  - hf-xet=1.1.8=py310h8cd5084_0
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - huggingface_hub=0.34.4=py310hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py310hca03da5_0
  - importlib-metadata=8.7.0=py310hca03da5_0
  - jansson=2.14=h80987f9_1
  - jinja2=3.1.6=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.9=py310haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libavif=1.3.0=h839b4eb_0
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libgrpc=1.74.1=h941cc20_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - libprotobuf=6.33.0=h6acce77_1
  - libre2-11=2025.11.05=hd4f4e8d_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.7.0=gpu_mps_h96286cc_201
  - libunistring=1.3=h1799b2a_0
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib=3.10.8=py310hca03da5_0
  - matplotlib-base=3.10.8=py310haa222d5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - multidict=6.7.0=py310h254cc4a_0
  - multiprocess=0.70.18=py310hca03da5_1
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.14.1=py310h5fbe615_0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.38.0=py310hca03da5_0
  - orc=2.2.0=hd6530ca_1
  - packaging=25.0=py310hca03da5_1
  - pandas=2.3.3=py310h3f644e9_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.1.0=py310h7b5562e_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - propcache=0.4.1=py310haa24f5a_0
  - pthread-stubs=0.3=h1a28f6b_1
  - pyarrow=21.0.0=py310h3f644e9_1
  - pycares=4.10.0=py310h091efcb_0
  - pycparser=2.23=py310hca03da5_0
  - pyparsing=3.2.5=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h80987f9_0
  - python_abi=3.10=3_cp310
  - pytorch=2.7.0=gpu_mps_py310h7b297f8_202
  - pytz=2025.2=py310hca03da5_0
  - pyyaml=6.0.3=py310h091b9d3_0
  - re2=2025.11.05=h1413154_0
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py310haa24f5a_0
  - requests=2.32.5=py310hca03da5_1
  - safetensors=0.6.2=py310h931abed_0
  - setuptools=80.10.1=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.2=hc0f95ea_1
  - sniffio=1.3.1=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - sympy=1.14.0=py310hca03da5_1
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.22.2=py310h99e1e97_0
  - tornado=6.5.4=py310haa24f5a_0
  - tqdm=4.67.1=py310h7eb115d_1
  - transformers=4.57.1=py310hca03da5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py310hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - uvloop=0.22.1=py310h8e34c70_1
  - wheel=0.46.3=py310hca03da5_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.22.0=py310haa24f5a_0
  - zipp=3.23.0=py310hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Applications/anaconda3/envs/imagy
