name: imagy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - python=3.10
  - pytorch
  - matplotlib
  - transformers
  - mahotas
  - zernike
  - opencv
  - scipy
prefix: /Applications/anaconda3/envs/imagy
